# This workflow will install Python dependencies, setup MySQL test database and run pytest with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SPM

on: [push, pull_request]

# permissions:
#   contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      DB_DATABASE: test_spm_db
      DB_USER: root
      DB_PASSWORD: 'root'
      DB_HOST: localhost

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup MySQL database
      run: |
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u ${{ env.DB_USER }} -p ${{ env.DB_PASSWORD }}
        mysql -e 'SHOW DATABASES;' -u ${{ env.DB_USER }} -p ${{ env.DB_PASSWORD }}
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest
