# This workflow will install Python dependencies, setup MySQL test database and run pytest with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: SPM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_NAME: test_spm_db
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOSTNAME: '127.0.0.1'
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
        - '8888:3306'
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Create env file
      run: |
        touch .env
        echo DB_HOSTNAME=${{ env.DB_HOSTNAME }} >> .env
        echo DB_PORT=3306 >> .env
        echo DB_USERNAME=${{ env.DB_USERNAME }} >> .env
        echo DB_PASSWORD=${{ env.DB_PASSWORD }} >> .env
        echo DB_NAME=${{ env.DB_NAME }} >> .env
        cat .env

    - name: Setup MySQL database
      run: |
        # sudo systemctl enable mysql.service
        # sudo systemctl start mysql.service
        mysql -h 127.0.0.1 --port 8888 -e 'CREATE DATABASE test;' -uroot -ppassword
        mysql -h 127.0.0.1 --port 8888 -e 'SHOW DATABASES;' -uroot -ppassword
#     - name: Lint with flake8
#       run: |
#         # stop the build if there are Python syntax errors or undefined names
#         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Test with pytest
    #   run: |
    #     pytest
